trigger:
- main
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'assembleDebug'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'AppGenesis-APK'
